center/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'center'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('search', views.doc_search, name = 'doc_search'),

]

printf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('',include('student.urls')),
    path('center/',include('center.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'student'

urlpatterns = [
    path('', views.document_upload, name = 'index')
]

center/models.py
from django.contrib.auth.models import (AbstractBaseUser, AbstractUser,
                                        BaseUserManager, PermissionsMixin,
                                        User, UserManager)
from django.db import models

# Create your models here.

class CenterUserManager(BaseUserManager):
    """

    """

    def create_user(self, email, password=None, type=None):
        if not email:
            raise ValueError('Пользователи должны иметь адрес электронной почты')

        user = self.model(email=self.normalize_email(email))

        user.type = type
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password, type):
        user = self.create_user(email, password=password, type=type)
        user.is_admin = True
        user.save(using=self._db)
        return user


class CenterUser(AbstractBaseUser, PermissionsMixin):
    """
    Custom user with email authorization
    """

    class Meta:
        verbose_name = u'Пользователь'
        verbose_name_plural = u'Пользователи'

    email = models.EmailField(('email address'), unique=True)
    type = models.IntegerField(('type'), default=0, blank=False)
    is_active = models.BooleanField(('active'), default=True)
    is_admin = models.BooleanField(default=False)

    objects = CenterUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['type']


    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, EMAIL_HOST_USER, [self.email], fail_silently=True, **kwargs)

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def get_type(self):
        return self.type

    @property
    def is_staff(self):
        return self.is_admin

class Profile(models.Model):
    """
    User profile
    """

    class Meta:
        verbose_name = u'Профиль'
        verbose_name_plural = u'Профили'

    user = models.OneToOneField(CenterUser, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Имя', max_length=64)
    last_name = models.CharField(verbose_name='Фамилия', max_length=64)

student/models.py
from django.db import models
from center.models import CenterUser
import os

# Create your models here.

def upload_path(instance, filename):
    return os.path.join(str(instance.__class__.__name__).lower() + '/', filename)

class Documents(models.Model):
    class Meta:
        verbose_name = u'Документ'
        verbose_name_plural = u'Документы'

    STATUS = (
        (1, 'Не печатан'),
        (2, 'Печатан')
    )

    file_name = models.CharField(max_length = 128, blank = True)
    document = models.FileField(upload_to = upload_path)
    code = models.CharField(max_length = 16)
    amount = models.IntegerField(default = 0)
    uploaded_at = models.DateTimeField(auto_now_add = True)
    printed_by = models.CharField(max_length = 128)
    state = models.IntegerField(verbose_name='Статус', choices=STATUS, default=1)

    def __str__(self):
        return self.document.name

    @property
    def filename(self):
        name = self.document.name
        return name

student/forms.py
from django import forms
from .models import Documents

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Documents
        fields = ('document',)
    
    def __init__(self, *args, **kwargs):
        super(DocumentForm, self).__init__(*args, **kwargs)
        self.fields['document'].widget.attrs.update({'class' : 'inputfile inputfile-5', 'id': 'file-upload'})

center/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from student.models import Documents
from django.http import JsonResponse
from django.core import serializers


# Create your views here.

@login_required(login_url = '/login')
def index(request):

    user = request.user
    return render(request, 'dashboard.html', {'user': user})


def doc_search(request):

    if request.method == 'POST':
        code = request.POST['doc_code']

        try:
            document = Documents.objects.filter(code = code)
            data = serializers.serialize('json', document)            
        except Exception as ex:
            print(ex)
            return JsonResponse({'error': 'Документ не найден!'})
            
        try:
            return render(request, 'print.html', {'data': document[0]})
        except Exception as ex:
            return JsonResponse({'error': 'Документ не найден!'})

        
        
        
        

student/views.py
from django.shortcuts import render, redirect
from .forms import DocumentForm
from .models import Documents
import time
from django.contrib import messages
from .models import Documents
from printf.settings import MEDIA_ROOT
# Create your views here.


import sys
import os
import subprocess
import re

def document_upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():

            file_name = request.FILES['document'].name
            
            order = form.save(commit=False)
            order.save()
            order.code = str(order.id)+ '-' + str(time.time())[:-8]
            order.file_name = file_name
            order.amount = 250

            order.save()
            converted = True

            if file_name.endswith('.doc') | file_name.endswith('.docx'):
                converted = doc2pdf(order.id)
            
            if converted:
                messages.info(request, 'Код документа: %s'%(order.code))
            else:
                messages.info(request, 'Не удалос конвертировать')

            return redirect('student:index')
    else:
        form = DocumentForm()
    return render(request, 'index.html', {
        'form': form
    })


def doc2pdf(order_id, timeout=None):

    order = Documents.objects.get(pk = order_id)

    source = os.path.join(MEDIA_ROOT, str(order.document))

    folder = os.path.join(MEDIA_ROOT, 'test')

    args = ['libreoffice', '--headless', '--convert-to', 'pdf', '--outdir', folder, source]

    try:
        process = subprocess.run(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=timeout)
        filename = re.search('-> (.*?) using filter', process.stdout.decode())
        
    except Exception as ex:
        return False

    if filename is None:
        return False
    else:
        os.remove(source)
        converted_file = filename.group(1).split('/test/')[-1]
        order.document = 'test/' + converted_file
        order.save()
        return True


    

center/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>

    {% block js_script %}{% endblock %}
</head>

<body>
{% block debug %}{{ debug }}{% endblock %}
{% if error_message %}
    <div class="alert alert-danger">
        <strong>{{ error_message|escape }}</strong>
    </div>
{% endif %}

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse float-right">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'center:index' %}">Главная</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<br><br><br>

{% block content %}(no content){% endblock %}


</body>
</html>

center/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}

<form class="form-inline" id = 'doc_search' method="POST" action="{% url 'center:doc_search' %}">
    {% csrf_token %}
    <div class="form-group mx-sm-3 mb-2">
      <label for="doc_code" class="sr-only">Код документа: </label>
      <input type="text" class="form-control" id="doc_code" name = 'doc_code'>
    </div>
    <button type="submit" class="btn btn-primary mb-2">Поиск</button>
</form>

<script>

    // $("#doc_search").submit(function(e) {

    //     var form = $(this);

    //     $.ajax({
    //         type: "POST",
    //         url: "{% url 'center:doc_search' %}",
    //         data: form.serialize(), // serializes the form's elements.
    //         success: function(data){
    //             console.log(data); // show response from the php script.
    //         }
    //     });

    //     e.preventDefault(); // avoid to execute the actual submit of the form.
    // });

</script>

{% endblock%}

center/templates/print.html
{% extends 'base.html' %}

{% block content %}
<style>

    #footer {
        min-height: 40px;
    }

    /* layout */
    #main-wrap {
        /* overflow to handle inner floating block */
        overflow: hidden;
    }

    #sidebar {
        float: left;
        width: 30%;
    }

    #content-wrap {
        float: right;
        width: 70%;
        height: 100%;
    }   

</style>

<div id="main-wrap">
    <div id="sidebar">
        <ul>
                <li>ID: {{data.id}}</li>
                <li>file_name: {{data.file_name}}</li>
                <li>amount: {{data.amount}}</li>
        </ul>

        <ul>
            <a href="{% url 'center:index' %}">Поиск</a>
        </ul>
    </div>
    <div id="content-wrap">
            <object style="width:100%; height: 500px;" data="{{data.document.url}}?#zoom=85&scrollbar=0&toolbar=0&navpanes=0" type="application/pdf">
    </div>
</div>

{% endblock%}

student/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js">
    </script>

    

    {% block js_script %}{% endblock %}
    {% block css_style %}{% endblock %}
</head>

<body>
{% block debug %}{{ debug }}{% endblock %}
{% if error_message %}
    <div class="alert alert-danger">
        <strong>{{ error_message|escape }}</strong>
    </div>
{% endif %}

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse float-right">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">Главная</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<br><br><br>

{% block content %}(no content){% endblock %}


</body>
</html>

student/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block js_script %}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<script>(function(e,t,n){var r=e.querySelectorAll("html")[0];r.className=r.className.replace(/(^|\s)no-js(\s|$)/,"$1js$2")})(document,window,0);</script>

{% endblock %}

  

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'demo.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'component.css' %}" />
  <div class="content">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="content">

            <div class="box">
                {{ form.document}}
              <label for="file-upload"><figure><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg></figure> <span></span></label>
            </div>				
          </div>   
        
        <button type="submit" class="btn btn-primary btn-lg">Загрузить</button>
      </form>     
    
      {% if messages %}
      <script>
        {% for message in messages %}
            swal({
              title: "Документ загружен!",
              text: "{{ message }}",
              icon: "success",
              button: "ОК",
            });
        {% endfor %}
      </script>
    {% endif %}
  </div>
  
<script src="{% static 'custom-file-input.js'%}"></script>
{% endblock %}